### ISSUE TITLE
Untouch window never pop-up, what should I do?

### ISSUE THREAD

**Issue by ilxq** [Mayuresh1611/Paper-Piano#4]
no error showed up, just on the touch window for so long time. Should I do anything to trigger untouch window? Thanks!

**Comment by Mayuresh1611** [comment]
Have you tried pressing 'q' or perhaps the collection of data is not complete, it takes 200 pics of both finger in touched and untouched state.
Then you get a try window where you can see if it detects touch or not. If not you can retrain model.

**Comment by ilxq** [comment]
![截屏2024-03-16 14 36 37](https://github.com/Mayuresh1611/Paper-Piano/assets/16127862/f93eec2f-3fcb-4030-9c67-85a2d5b11c63)
I thought we should select the 1st - retrain model before we go to the 2nd - start paper piano, right?
Attached picture is when I do the retrain. Fingers can be recognized perfectly in the touch window, but just can't jump to untouch window automatically. I stay in the touch window stage for more than 5 mins...

**Comment by Mayuresh1611** [comment]
> I thought we should select the 1st - retrain model before we go to the 2nd - start paper piano, right?

Heyy actually, If there is no saved model in the folder, you will be automatically taken to training stage, if there is saved model already, you can either retrain or choose to play piano.

Now coming to your problem, you are currently in touch tracking window, it is their to position your fingers so that the box covering the finger should cover finger as well as area below it ( for shadows and positions ). So you will move forward when you press Q key while in window. I hope this solves it.

**Comment by ilxq** [comment]
![截屏2024-03-16 15 45 53](https://github.com/Mayuresh1611/Paper-Piano/assets/16127862/f846f4b2-b306-43e2-8b30-a022de372c2d)
Thank you for your quick response! Tried lower the camera, still keep on the stage of touch window...
And I did reloaded the zip and run the program. Not showed the menu with 3 options now...didn't know why...
![截屏2024-03-16 15 51 09](https://github.com/Mayuresh1611/Paper-Piano/assets/16127862/cac4fad8-9802-4209-8f1a-59ae65bcae28)
Attaching the camera view and terminal view fyi...Thanks!

**Comment by Mayuresh1611** [comment]
No actually there is not trained model yet so you are directly moved to training stage, and press q when touch tracking window pops, then touch the finger to surface and try to give different angles of touched finger, then when 200 samples are completed window will close and then lift finger to collect samples for untouched data!
I should do something about the command line too, it is getting really messy!

Also can you do GUI stuff if possible, That would be much better instead of command line ig,

**Comment by ilxq** [comment]
Wow! Can't wait to tell you it worked! Magical "Q"!!! 
Nice project and looking forward to the enhancement - tone pattern align with piano, and to make multi- fingers work！
Much appreciate! Nice weekend!

**Comment by Mayuresh1611** [comment]
> make multi- fingers work！

yepp! currently working on that! Have good day!
